[sssd]
domains = corp.local
config_file_version = 2
services = nss, pam

[domain/corp.local]
default_shell = /bin/bash
krb5_store_password_if_offline = True
cache_credentials = True
krb5_realm = CORP.LOCAL
realmd_tags = manages-system joined-with-adcli
id_provider = ad
ad_domain = corp.local
fallback_homedir = /home/%u
use_fully_qualified_names = False
ldap_id_mapping = True

# 限制誰能 ssh 登入
access_provider = simple
simple_allow_groups = sftp_users, dept_it_admins, dept_archi_view, dept_hr_view, dept_fin_view, dept_ops_view

# 啟用 enumeration (列出所有 AD 帳號, 有 perf cost, 看需要)
enumerate = False
